# Generated by Django 5.2.17 on 2026-08-11 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(default='Workshop', max_length=100)),
                ('venue', models.CharField(default='Campus Auditorium', max_length=200)),
                ('capacity', models.PositiveIntegerField(default=100)),
                ('poster_image', models.URLField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('visible_from', models.DateTimeField(blank=True, null=True)),
                ('visible_until', models.DateTimeField(blank=True, null=True)),
                ('registration_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms.form')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
