# Generated by Django 5.2.17 on 2026-08-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('forms', '0008_answer_forms_answe_respons_f082af_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_time', 'visible_from'], name='events_even_start_t_4df89a_idx'),
        ),
    ]
