# Generated by Django 5.2.17 on 2026-09-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_events_even_start_t_4df89a_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('LIVE', 'Live'), ('CLOSED', 'Closed')], default='LIVE', max_length=20),
        ),
    ]
