# Generated by Django 5.2.17 on 2026-09-02 10:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('COLLEGE', 'College / University'), ('CHAPTER', 'Student Chapter'), ('PARTNER', 'Partner Organization'), ('COMMUNITY', 'Tech Community')], default='COLLEGE', max_length=20)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage discount, e.g. 15.00 for 15%', max_digits=5)),
                ('discount_fixed', models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed amount discount in INR', max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='user',
            name='club_id',
            field=models.CharField(blank=True, db_index=True, help_text='Permanent unique Club ID (e.g. 25SCC277). Immutable once assigned.', max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_from',
            field=models.CharField(default='SELF_REGISTRATION', help_text='Origin of account creation: LEGACY_IMPORT, FORM, ADMIN, SELF_REGISTRATION', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='membership_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('ALUMNI', 'Alumni'), ('PENDING', 'Pending')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by_raw',
            field=models.CharField(blank=True, help_text='Raw unlinked referrer name from legacy imports', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by_user',
            field=models.ForeignKey(blank=True, help_text='Resolved club member who referred or onboarded this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='registered_at',
            field=models.DateTimeField(blank=True, help_text='Historical date when the member joined the club', null=True),
        ),
        migrations.CreateModel(
            name='ClubIDSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prefix', models.CharField(default='SCC', max_length=10)),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('next_sequence', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['prefix', '-year'],
                'unique_together': {('prefix', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_filename', models.CharField(max_length=255)),
                ('source_type', models.CharField(default='MEMBER_BACKUP', max_length=50)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=128, null=True, unique=True)),
                ('status', models.CharField(choices=[('PREVIEWED', 'Previewed'), ('COMMITTED', 'Committed'), ('FAILED', 'Failed')], default='PREVIEWED', max_length=20)),
                ('mapping_snapshot', models.JSONField(default=dict)),
                ('validation_snapshot', models.JSONField(default=dict)),
                ('rows_data', models.JSONField(default=list, help_text='Parsed cleaned rows for atomic commit')),
                ('total_rows', models.IntegerField(default=0)),
                ('valid_rows', models.IntegerField(default=0)),
                ('conflict_rows', models.IntegerField(default=0)),
                ('new_users_count', models.IntegerField(default=0)),
                ('updated_users_count', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAffiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.affiliate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
                'unique_together': {('user', 'affiliate')},
            },
        ),
    ]
