# Generated by Django 5.2.17 on 2026-09-02 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_affiliate_alter_user_options_user_club_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useraffiliate',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='UserAffiliate',
        ),
        migrations.DeleteModel(
            name='Affiliate',
        ),
    ]
