# Generated by Django 5.2.17 on 2026-09-02 17:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def populate_password_status(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    for user in User.objects.all():
        raw_pwd = user.password or ""
        # Django unusable passwords start with '!' or '!*' or are empty
        if not raw_pwd or raw_pwd.startswith('!'):
            user.password_status = 'NEEDS_SETUP'
        else:
            user.password_status = 'ACTIVE'
        user.save(update_fields=['password_status'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_useraffiliate_affiliate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_status',
            field=models.CharField(choices=[('ACTIVE', 'Password Active'), ('NEEDS_SETUP', 'Password Setup Required')], db_index=True, default='ACTIVE', help_text='Tracks credential readiness: ACTIVE for normal users, NEEDS_SETUP for backup-imported accounts', max_length=20),
        ),
        migrations.CreateModel(
            name='PasswordSetupToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_setup_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token_hash', 'is_used'], name='accounts_pa_token_h_f8c3cf_idx'), models.Index(fields=['user', 'is_used'], name='accounts_pa_user_id_69ba77_idx')],
            },
        ),
        migrations.RunPython(populate_password_status, migrations.RunPython.noop),
    ]
