# Generated by Django 5.2.17 on 2026-09-19 16:13
#
# DEPLOYMENT NOTE — pre-flight data check required on any environment other
# than this branch's own dev database: this migration adds a DB-level
# unique=True constraint to accounts_user.roll_number with no pre-flight
# check of existing data. This dev DB has been verified clean (0 duplicate
# roll_number values, 0 blank-string collisions — note the empty string ''
# is NOT NULL-exempt from a unique constraint, only actual NULL is), but a
# different environment with unknown/dirty legacy data could hard-fail when
# this migration applies. Before applying to any other environment, run a
# check for duplicate or blank-string roll_number values and clean them up
# first, e.g.:
#
#   SELECT roll_number, COUNT(*) FROM accounts_user
#   WHERE roll_number IS NOT NULL GROUP BY roll_number HAVING COUNT(*) > 1;
#
# Documentation-only note — the already-applied migration and its dependency
# chain are intentionally left unchanged.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_password_status_passwordsetuptoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roll_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
