# Generated by Django 5.2.17 on 2026-09-19 16:13
# Renamed from 0005_roll_number_unique.py after this exact migration failed
# applying to a real deployment:
#
#   psycopg2.errors.UniqueViolation: could not create unique index
#   "accounts_user_roll_number_d4c665ff_uniq"
#   DETAIL:  Key (roll_number)=(xyz) is duplicated.
#
# The dev database this migration was originally authored and tested against
# had no duplicates, but production did (a placeholder value shared by more
# than one legacy account). Fix: 0005_cleanup_duplicate_roll_numbers now runs
# first and nulls out placeholder/duplicate values, so this AlterField always
# lands on a column that's actually unique. Renaming (rather than leaving
# this as 0005 and inserting the cleanup elsewhere in the graph) was safe
# because — confirmed from the failing deploy's own traceback — this
# migration had never successfully applied anywhere but the local dev
# database that originally authored it; Django wraps each Postgres migration
# in its own transaction, so the failed attempt left every other environment
# at "0004 applied, no further," nothing to reconcile after the fact.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_cleanup_duplicate_roll_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roll_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
