# Generated by Django 5.2.17 on 2026-09-19 17:20

from django.db import migrations, models


def split_member_role(apps, schema_editor):
    """
    One-time data migration: existing MEMBER rows split by whether they
    already have a club_id. Verified against the live dataset before writing
    this migration — 26 MEMBER rows: 12 with a club_id (-> AFFILIATE), 14
    without (-> NON_AFFILIATE). VOLUNTEER/JUDGE/CLUB_LEAD/ADMIN rows are
    untouched by both filters below (they don't match role='MEMBER').
    """
    User = apps.get_model('accounts', 'User')
    User.objects.filter(role='MEMBER', club_id__isnull=False).update(role='AFFILIATE')
    User.objects.filter(role='MEMBER', club_id__isnull=True).update(role='NON_AFFILIATE')


def unsplit_member_role(apps, schema_editor):
    """Reverse: collapse AFFILIATE/NON_AFFILIATE back to MEMBER, for `migrate` rollback symmetry."""
    User = apps.get_model('accounts', 'User')
    User.objects.filter(role__in=['AFFILIATE', 'NON_AFFILIATE']).update(role='MEMBER')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_roll_number_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('AFFILIATE', 'Affiliate'), ('NON_AFFILIATE', 'Non-Affiliate'), ('VOLUNTEER', 'Volunteer'), ('JUDGE', 'Judge'), ('CLUB_LEAD', 'Club Lead'), ('ADMIN', 'Admin')], default='NON_AFFILIATE', max_length=20),
        ),
        migrations.RunPython(split_member_role, reverse_code=unsplit_member_role),
    ]
