# Generated by Django 5.2.17 on 2026-09-19 17:20

from django.db import migrations, models


def split_member_role(apps, schema_editor):
    """
    One-time data migration: existing MEMBER rows split by whether they
    already have a club_id. Verified against the live dataset before writing
    this migration — 26 MEMBER rows: 12 with a club_id (-> AFFILIATE), 14
    without (-> NON_AFFILIATE). VOLUNTEER/JUDGE/CLUB_LEAD/ADMIN rows are
    untouched by both filters below (they don't match role='MEMBER').

    NOTE — down-then-up asymmetry: this forward function is not a true
    inverse of `unsplit_member_role` under a rollback-then-reapply sequence.
    The invariant on this branch is one-directional: AFFILIATE requires a
    club_id, but NON_AFFILIATE-with-a-club_id is a legitimate state (e.g. a
    non-affiliate who was later issued a club_id through some other flow).
    If the migration is rolled back, `unsplit_member_role` collapses BOTH
    AFFILIATE and NON_AFFILIATE rows to MEMBER, and this function's
    `club_id__isnull=False` check then re-promotes that NON_AFFILIATE-with-
    club_id row straight back to AFFILIATE on re-apply — silently changing
    its role from what it actually was before the rollback. This is a known,
    accepted limitation (documentation-only; the logic is intentionally left
    unchanged since this migration is already applied) — a rollback runbook
    must not assume `migrate` down then up round-trips role data cleanly for
    any NON_AFFILIATE user who holds a club_id.
    """
    User = apps.get_model('accounts', 'User')
    User.objects.filter(role='MEMBER', club_id__isnull=False).update(role='AFFILIATE')
    User.objects.filter(role='MEMBER', club_id__isnull=True).update(role='NON_AFFILIATE')


def unsplit_member_role(apps, schema_editor):
    """
    Reverse: collapse AFFILIATE/NON_AFFILIATE back to MEMBER, for `migrate`
    rollback symmetry.

    NOTE — down-then-up asymmetry: see the matching note on
    `split_member_role` above. This function cannot distinguish "was
    originally AFFILIATE" from "was originally NON_AFFILIATE but happens to
    hold a club_id" — both collapse to the same MEMBER row here, and a
    subsequent re-apply of `split_member_role` will re-promote the latter to
    AFFILIATE, which is incorrect for that user. Not fixed here: restructuring
    an already-applied migration's logic is riskier than documenting the gap.
    """
    User = apps.get_model('accounts', 'User')
    User.objects.filter(role__in=['AFFILIATE', 'NON_AFFILIATE']).update(role='MEMBER')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_roll_number_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('AFFILIATE', 'Affiliate'), ('NON_AFFILIATE', 'Non-Affiliate'), ('VOLUNTEER', 'Volunteer'), ('JUDGE', 'Judge'), ('CLUB_LEAD', 'Club Lead'), ('ADMIN', 'Admin')], default='NON_AFFILIATE', max_length=20),
        ),
        migrations.RunPython(split_member_role, reverse_code=unsplit_member_role),
    ]
