# Generated by Django 5.2.17 on 2026-09-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='status',
            field=models.CharField(choices=[('LIVE', 'Live'), ('CLOSED', 'Closed')], default='LIVE', max_length=20),
        ),
    ]
