# Generated by Django 5.2.17 on 2026-10-02 06:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0020_formfield_profile_field'),
        ('hackathons', '0003_alter_team_leader'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='max_team_size',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='min_team_size',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='registration_closes_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='registration_opens_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='required_profile_fields',
            field=models.JSONField(blank=True, default=list, help_text="apps.forms.models.ProfileField keys every member must have filled in on their profile, e.g. ['phone_number', 'branch']."),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='team_edits_locked',
            field=models.BooleanField(default=False, help_text='Freeze team name / problem statement / membership changes by participants (admins can still edit).'),
        ),
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('FORMING', 'Forming'), ('REGISTERED', 'Registered'), ('DISQUALIFIED', 'Disqualified'), ('WITHDRAWN', 'Withdrawn')], default='FORMING', max_length=20),
        ),
        migrations.CreateModel(
            name='ProblemStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('max_teams', models.PositiveIntegerField(blank=True, help_text='Blank = unlimited.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_statements', to='hackathons.hackathon')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='team',
            name='problem_statement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='hackathons.problemstatement'),
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='UPCOMING', max_length=10)),
                ('results_published', models.BooleanField(default=False)),
                ('details_form', models.ForeignKey(blank=True, help_text="Form shortlisted teams' leaders fill in to (re-)submit details for this round.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hackathon_rounds', to='forms.form')),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='hackathons.hackathon')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HackathonAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('INFO', 'Info'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('URGENT', 'Urgent')], default='INFO', max_length=10)),
                ('audience', models.CharField(choices=[('PUBLIC', 'Everyone (public)'), ('PARTICIPANTS', 'All registered participants'), ('ROUND_ALL', 'All teams in a round'), ('ROUND_SHORTLISTED', 'Shortlisted teams in a round'), ('TEAMS', 'Specific teams')], default='PUBLIC', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('publish_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('send_email', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='hackathons.hackathon')),
                ('target_teams', models.ManyToManyField(blank=True, related_name='targeted_announcements', to='hackathons.team')),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='hackathons.round')),
            ],
            options={
                'ordering': ['-publish_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RoundEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SHORTLISTED', 'Shortlisted'), ('REJECTED', 'Not Shortlisted')], default='PENDING', max_length=12)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal — never shown to the team.')),
                ('feedback', models.TextField(blank=True, help_text='Shown to the team once results are published.')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('details_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hackathon_round_entries', to='forms.response')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='hackathons.round')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_entries', to='hackathons.team')),
            ],
            options={
                'ordering': ['round__order', 'team__name'],
            },
        ),
        migrations.CreateModel(
            name='TeamInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_invites', to='hackathons.hackathon')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackathon_invites', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='hackathons.team')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('LEADER', 'Leader'), ('MEMBER', 'Member')], default='MEMBER', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='hackathons.hackathon')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='hackathons.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackathon_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='problemstatement',
            constraint=models.UniqueConstraint(fields=('hackathon', 'code'), name='uniq_problem_statement_code_per_hackathon'),
        ),
        migrations.AddConstraint(
            model_name='round',
            constraint=models.UniqueConstraint(fields=('hackathon', 'order'), name='uniq_round_order_per_hackathon'),
        ),
        migrations.AddConstraint(
            model_name='roundentry',
            constraint=models.UniqueConstraint(fields=('round', 'team'), name='uniq_round_entry_per_team'),
        ),
        migrations.AddConstraint(
            model_name='teaminvite',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('team', 'invited_user'), name='uniq_pending_invite_per_team_user'),
        ),
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.UniqueConstraint(fields=('hackathon', 'user'), name='uniq_one_team_per_user_per_hackathon'),
        ),
    ]
