# Generated by Django 5.2.17 on 2026-10-02 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0006_team_members_through_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='problem_statement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='hackathons.problemstatement'),
        ),
    ]
