# Generated by Django 5.2.17 on 2026-10-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0008_open_innovation_and_generated_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundentry',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal only, never shown to the team.'),
        ),
    ]
