# Generated by Django 5.2.17 on 2026-09-02 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_id', models.CharField(max_length=100)),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'XLSX'), ('json', 'JSON')], default='csv', max_length=10)),
                ('row_scope', models.CharField(default='all_filtered', max_length=20)),
                ('column_scope', models.CharField(default='visible', max_length=20)),
                ('selected_record_ids', models.JSONField(blank=True, default=list)),
                ('filter_snapshot', models.JSONField(blank=True, default=dict)),
                ('column_keys', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='QUEUED', max_length=20)),
                ('row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dmc_export_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='core_export_status_2ad959_idx'), models.Index(fields=['created_by', 'created_at'], name='core_export_created_899602_idx')],
            },
        ),
    ]
