# Generated by Django 5.2.17 on 2026-09-02 16:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_emailtemplate_emailjob_emaildelivery'),
        ('forms', '0012_form_enable_prefill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_sha256', models.CharField(db_index=True, max_length=64)),
                ('file_size_bytes', models.PositiveIntegerField()),
                ('file_storage_path', models.CharField(blank=True, max_length=500)),
                ('mime_type', models.CharField(default='application/octet-stream', max_length=100)),
                ('file_format', models.CharField(max_length=10)),
                ('headers', models.JSONField(default=list)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('suggested_domain', models.CharField(blank=True, max_length=50)),
                ('suggestion_confidence', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Intake'), ('PARSED', 'Parsed & Preserved'), ('AWAITING_DOMAIN_SELECTION', 'Awaiting Domain Selection'), ('READY', 'Ready for Import'), ('PARTIALLY_IMPORTED', 'Partially Imported'), ('ARCHIVED_RAW', 'Archived in Raw Vault'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=30)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportAttempt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=128, null=True, unique=True)),
                ('target_domain', models.CharField(max_length=50)),
                ('column_mapping', models.JSONField(default=dict)),
                ('unmapped_columns', models.JSONField(default=list)),
                ('required_fields_satisfied', models.BooleanField(default=False)),
                ('schema_confidence_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_records', models.IntegerField(default=0)),
                ('valid_records', models.IntegerField(default=0)),
                ('conflict_records', models.IntegerField(default=0)),
                ('inserted_records', models.IntegerField(default=0)),
                ('updated_records', models.IntegerField(default=0)),
                ('validation_summary', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PREVIEWED', 'Previewed'), ('COMMITTED', 'Committed'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed')], default='PREVIEWED', max_length=20)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('backup_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_attempts', to='core.backupjob')),
                ('committed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('target_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.form')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawBackupArchive',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(default='UNKNOWN_RAW', max_length=50)),
                ('headers', models.JSONField(default=list)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(default=dict)),
                ('backup_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='raw_archive', to='core.backupjob')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_row_number', models.PositiveIntegerField()),
                ('raw_data', models.JSONField(default=dict, help_text='Includes all unmapped legacy columns')),
                ('normalized_data', models.JSONField(default=dict)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('SKIP', 'Skip'), ('CONFLICT', 'Conflict')], max_length=20)),
                ('is_valid', models.BooleanField(default=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=50)),
                ('error_message', models.TextField(blank=True, default='')),
                ('target_object_id', models.CharField(blank=True, default='', max_length=100)),
                ('import_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='core.importattempt')),
            ],
            options={
                'ordering': ['source_row_number'],
                'indexes': [models.Index(fields=['import_attempt', 'source_row_number'], name='core_import_import__9ad25b_idx')],
            },
        ),
        migrations.CreateModel(
            name='RawBackupRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.PositiveIntegerField()),
                ('row_data', models.JSONField(default=dict)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='core.rawbackuparchive')),
            ],
            options={
                'ordering': ['row_number'],
                'indexes': [models.Index(fields=['archive', 'row_number'], name='core_rawbac_archive_053841_idx')],
            },
        ),
    ]
