# Generated by Django 5.2.17 on 2026-09-12 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_backupjob_importattempt_rawbackuparchive_importrow_and_more'),
        ('forms', '0015_drop_formfield_is_primary_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildelivery',
            name='response',
            field=models.ForeignKey(blank=True, help_text='Set when this delivery is a form-submission confirmation email, linking it back to the response that triggered it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmation_email_deliveries', to='forms.response'),
        ),
    ]
