# Generated by Django 5.2.17 on 2026-09-22 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_emaildelivery_response'),
        ('forms', '0017_form_attendance_days_form_attendance_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importattempt',
            name='target_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms.form'),
        ),
    ]
