# Generated by Django 5.2.17 on 2026-08-20 08:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codequest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', 'is_correct'], name='codequest_s_user_id_f0bf04_idx'),
        ),
    ]
