# Generated by Django 5.2.17 on 2026-08-15 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_form_category_form_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='allow_edits_until',
            field=models.DateTimeField(blank=True, help_text='Deadline after which responses are locked', null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='allow_multiple_responses',
            field=models.BooleanField(default=False, help_text='Allow a user to submit multiple times'),
        ),
        migrations.AddField(
            model_name='form',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Schema version incremented on form updates'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='conditional_logic',
            field=models.JSONField(blank=True, default=dict, help_text="Visibility rules e.g. {'if': 'field_id', 'equals': 'val'}"),
        ),
        migrations.AddField(
            model_name='response',
            name='created_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_manual_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='response',
            name='is_manual_entry',
            field=models.BooleanField(default=False, help_text='Flagged if added via Admin Manual Override on closed form'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('PARAGRAPH', 'Paragraph'), ('EMAIL', 'Email'), ('NUMBER', 'Number'), ('DROPDOWN', 'Dropdown'), ('RADIO', 'Radio Button'), ('CHECKBOX', 'Checkbox'), ('FILE', 'File Upload'), ('MULTI_FILE', 'Multi File Upload'), ('DATE', 'Date'), ('SECTION', 'Section Header')], default='TEXT', max_length=20),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='validation_rules',
            field=models.JSONField(blank=True, default=dict, help_text="Validation rules e.g. {'max_size_mb': 10, 'allowed_extensions': ['pdf']}"),
        ),
    ]
