# Generated by Django 5.2.17 on 2026-08-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_form_allow_edits_until_form_allow_multiple_responses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft-deleted fields preserved for historical response export'),
        ),
        migrations.AddField(
            model_name='response',
            name='form_version',
            field=models.PositiveIntegerField(default=1, help_text='Form schema version snapshot at submission time'),
        ),
        migrations.AddField(
            model_name='response',
            name='is_test_submission',
            field=models.BooleanField(default=False, help_text='Isolated preview test submission flag'),
        ),
    ]
