# Generated by Django 5.2.17 on 2026-08-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_formfield_is_deleted_response_form_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='max_value',
            field=models.IntegerField(blank=True, help_text='Maximum value for RATING / LINEAR_SCALE', null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='min_value',
            field=models.IntegerField(blank=True, help_text='Minimum value for RATING / LINEAR_SCALE', null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='rows',
            field=models.JSONField(blank=True, default=list, help_text='Row labels for MATRIX field types'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='conditional_logic',
            field=models.JSONField(blank=True, default=dict, help_text="Multi-rule visibility: {'logic': 'AND', 'rules': [{'if': field_id, 'operator': 'equals', 'value': 'x'}]}. Legacy single-rule format {'if': field_id, 'equals': 'x'} is also supported for backward compatibility."),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('PARAGRAPH', 'Paragraph'), ('EMAIL', 'Email'), ('NUMBER', 'Number'), ('PHONE', 'Phone'), ('URL', 'URL'), ('DROPDOWN', 'Dropdown'), ('RADIO', 'Radio Button'), ('CHECKBOX', 'Checkbox'), ('FILE', 'File Upload'), ('MULTI_FILE', 'Multi File Upload'), ('DATE', 'Date'), ('TIME', 'Time'), ('SECTION', 'Section Header'), ('RATING', 'Star Rating'), ('LINEAR_SCALE', 'Linear Scale'), ('MATRIX_RADIO', 'Matrix Radio Grid'), ('MATRIX_CHECKBOX', 'Matrix Checkbox Grid'), ('SIGNATURE', 'Signature Capture')], default='TEXT', max_length=20),
        ),
    ]
