# Generated by Django 5.2.17 on 2026-08-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_bulkingestsession_membernote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed'), ('SCHEDULED', 'Scheduled'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20),
        ),
    ]
