# Generated by Django 5.2.17 on 2026-08-20 08:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_update_form_status_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['response', 'field'], name='forms_answe_respons_f082af_idx'),
        ),
        migrations.AddIndex(
            model_name='form',
            index=models.Index(fields=['status', 'open_at'], name='forms_form_status_31f629_idx'),
        ),
        migrations.AddIndex(
            model_name='form',
            index=models.Index(fields=['created_at'], name='forms_form_created_1fdbde_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['form', 'submitted_at'], name='forms_respo_form_id_72f51e_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['user', 'submitted_at'], name='forms_respo_user_id_9f8df0_idx'),
        ),
    ]
