# Generated by Django 5.2.17 on 2026-08-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_answer_forms_answe_respons_f082af_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
