# Generated by Django 5.2.17 on 2026-08-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_alter_form_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
