# Generated by Django 5.2.17 on 2026-08-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_alter_form_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='allow_response_editing',
            field=models.BooleanField(default=True, help_text='Allow users to view and update their previously submitted response'),
        ),
        migrations.AddField(
            model_name='form',
            name='max_responses_per_user',
            field=models.PositiveIntegerField(default=1, help_text='Maximum allowed submissions per user (1 for single submission)'),
        ),
    ]
