# Generated by Django 5.2.17 on 2026-08-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_form_allow_response_editing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='enable_prefill',
            field=models.BooleanField(default=True, help_text='Automatically pre-fill student profile details when limit is 1'),
        ),
    ]
