# Generated by Django 5.2.17 on 2026-09-05 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_backupjob_importattempt_rawbackuparchive_importrow_and_more'),
        ('forms', '0012_form_enable_prefill'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='club_id_enabled',
            field=models.BooleanField(default=False, help_text="On each completed submission, find-or-create a club member (by the mapped email field) and allocate a permanent Club ID if they don't already have one."),
        ),
        migrations.AddField(
            model_name='form',
            name='club_id_field_mapping',
            field=models.JSONField(blank=True, default=dict, help_text="Maps profile attributes to this form's own field IDs, e.g. {'email': 12, 'full_name': 13, 'phone_number': 14, 'branch': 15, 'roll_number': 16}. 'email' is required when club_id_enabled is True."),
        ),
        migrations.AddField(
            model_name='form',
            name='club_id_prefix',
            field=models.CharField(default='SCC', help_text="2-6 uppercase letters, e.g. 'SCC'. Combined with the submission year: '25SCC278'.", max_length=10),
        ),
        migrations.AddField(
            model_name='form',
            name='confirmation_email_enabled',
            field=models.BooleanField(default=False, help_text='Send an EmailTemplate-based confirmation email to the submitter when their response completes.'),
        ),
        migrations.AddField(
            model_name='form',
            name='confirmation_email_template',
            field=models.ForeignKey(blank=True, help_text='Template dispatched on submission when confirmation_email_enabled is True.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmation_forms', to='core.emailtemplate'),
        ),
    ]
