# Generated by Django 5.2.17 on 2026-09-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0015_drop_formfield_is_primary_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='max_total_responses',
            field=models.PositiveIntegerField(blank=True, help_text='Auto-close the form once this many total (non-test) responses are received. Leave blank for unlimited.', null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='prevent_duplicate_email_answers',
            field=models.BooleanField(default=False, help_text="Reject a submission if any EMAIL-type field's value has already been used to answer this same form (excluding test submissions). Off by default — some forms legitimately expect one email to submit more than once (e.g. a parent registering several children)."),
        ),
    ]
