# Generated by Django 5.2.17 on 2026-09-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0016_form_max_total_responses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='attendance_days',
            field=models.PositiveIntegerField(default=1, help_text='Number of days attendance is tracked for, starting from attendance_start_date (1-30).'),
        ),
        migrations.AddField(
            model_name='form',
            name='attendance_enabled',
            field=models.BooleanField(default=False, help_text="Activate QR-code attendance tracking for this form's registrants (workshop/hackathon check-in)."),
        ),
        migrations.AddField(
            model_name='form',
            name='attendance_sessions_per_day',
            field=models.PositiveIntegerField(default=1, help_text='Sessions scanned per day: 1 (Morning), 2 (Morning + Afternoon), or 3 (Morning + Afternoon + Evening).'),
        ),
        migrations.AddField(
            model_name='form',
            name='attendance_start_date',
            field=models.DateField(blank=True, help_text='First day of the attendance schedule. Required when attendance_enabled is True.', null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='attendance_window_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='If set, a session can only be scanned within this many minutes of its scheduled start. Leave blank for no time restriction.', null=True),
        ),
    ]
