# Generated by Django 5.2.17 on 2026-09-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0017_form_attendance_days_form_attendance_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='club_id_verification_enabled',
            field=models.BooleanField(default=False, help_text="On each submission, verify the mapped Club ID field is a registered member and that the other mapped fields match that member's record. The 'club_id' key of club_id_field_mapping supplies which field holds the submitted Club ID."),
        ),
        migrations.AlterField(
            model_name='form',
            name='club_id_field_mapping',
            field=models.JSONField(blank=True, default=dict, help_text="Maps profile attributes to this form's own field IDs, e.g. {'email': 12, 'full_name': 13, 'phone_number': 14, 'branch': 15, 'roll_number': 16, 'club_id': 17}. 'email' is required when club_id_enabled is True; 'club_id' is required when club_id_verification_enabled is True."),
        ),
    ]
