# Generated by Django 5.2.17 on 2026-09-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0018_form_club_id_verification_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('PARAGRAPH', 'Paragraph'), ('EMAIL', 'Email'), ('NUMBER', 'Number'), ('PHONE', 'Phone'), ('URL', 'URL'), ('DROPDOWN', 'Dropdown'), ('RADIO', 'Radio Button'), ('CHECKBOX', 'Checkbox'), ('FILE', 'File Upload'), ('MULTI_FILE', 'Multi File Upload'), ('DATE', 'Date'), ('TIME', 'Time'), ('SECTION', 'Section Header'), ('RATING', 'Star Rating'), ('LINEAR_SCALE', 'Linear Scale'), ('MATRIX_RADIO', 'Matrix Radio Grid'), ('MATRIX_CHECKBOX', 'Matrix Checkbox Grid'), ('SIGNATURE', 'Signature Capture'), ('CLUB_ID', 'Club ID')], default='TEXT', max_length=20),
        ),
    ]
