# Generated by Django 5.2.17 on 2026-10-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0020_formfield_profile_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='prevent_duplicate_email_answers',
            field=models.BooleanField(default=False, help_text="Reject a submission if any EMAIL-type field's value has already been used to answer this same form (excluding test submissions). Off by default. Some forms legitimately expect one email to submit more than once (e.g. a parent registering several children)."),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='profile_field',
            field=models.CharField(blank=True, choices=[('full_name', 'Full Name'), ('email', 'Email'), ('phone_number', 'Phone Number'), ('branch', 'Branch'), ('roll_number', 'Roll Number'), ('year', 'Year'), ('club_id', 'Club ID')], help_text="When set, this question is never asked of the user: it's resolved server-side from the submitter's own profile at submission time (any client-supplied value for it is discarded) and shown read-only in the registration confirmation. Leave blank for an ordinary user-answered question.", max_length=20, null=True),
        ),
    ]
