# Generated by Django 5.2.17 on 2026-10-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0021_help_text_without_em_dashes'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='confirmation_notification_enabled',
            field=models.BooleanField(default=False, help_text='Send an in-app notification to the submitter when their response completes.'),
        ),
        migrations.AddField(
            model_name='form',
            name='notification_message',
            field=models.TextField(blank=True, default='', help_text="Custom message for the in-app confirmation notification. Defaults to 'Your response for <Form Title> has been successfully recorded.'"),
        ),
        migrations.AddField(
            model_name='form',
            name='notification_title',
            field=models.CharField(blank=True, default='', help_text="Custom title for the in-app confirmation notification. Defaults to 'Response Recorded: <Form Title>'", max_length=200),
        ),
        migrations.AddField(
            model_name='form',
            name='notify_admin_on_submission',
            field=models.BooleanField(default=False, help_text='Send an in-app notification to the form creator / admin when a response is submitted.'),
        ),
        migrations.AddField(
            model_name='form',
            name='notify_members_on_publish',
            field=models.BooleanField(default=False, help_text='Broadcast an in-app notification to all members when this form is published.'),
        ),
    ]
