from django.db import models
from django.db.models import Q
from django.db.models.functions import Lower
from django.conf import settings
from django.utils import timezone
from apps.core.models import TimeStampedModel
from apps.forms.models import Form, Response as FormResponse
from apps.announcements.models import AnnouncementType


class HackathonStatus(models.TextChoices):
    LIVE = 'LIVE', 'Live'
    CLOSED = 'CLOSED', 'Closed'


class Hackathon(TimeStampedModel):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    is_flagship = models.BooleanField(default=False, help_text="Flag as IconCoders flagship edition")
    theme = models.CharField(max_length=255)
    description = models.TextField()
    prize_pool = models.CharField(max_length=100, default='₹50,000')
    banner_image = models.URLField(blank=True, null=True)
    status = models.CharField(max_length=20, choices=HackathonStatus.choices, default=HackathonStatus.LIVE)

    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    visible_from = models.DateTimeField(blank=True, null=True)
    visible_until = models.DateTimeField(blank=True, null=True)

    # Legacy: a generic Form used as the registration link before team
    # formation existed. Not used by the team-registration flow.
    registration_form = models.ForeignKey(Form, on_delete=models.SET_NULL, null=True, blank=True)

    # --- Team registration settings ------------------------------------------
    registration_opens_at = models.DateTimeField(blank=True, null=True)
    registration_closes_at = models.DateTimeField(blank=True, null=True)
    min_team_size = models.PositiveIntegerField(default=1)
    max_team_size = models.PositiveIntegerField(default=4)
    team_edits_locked = models.BooleanField(
        default=False,
        help_text="Freeze team name / problem statement / membership changes by participants (admins can still edit).",
    )
    allow_open_innovation = models.BooleanField(
        default=True,
        help_text="Let teams bring their own problem (title, description, domain) instead of picking an admin-defined statement.",
    )
    required_profile_fields = models.JSONField(
        default=list, blank=True,
        help_text="apps.forms.models.ProfileField keys every member must have filled in on their profile, e.g. ['phone_number', 'branch'].",
    )

    def __str__(self):
        flag_str = " (IconCoders Flagship)" if self.is_flagship else ""
        return f"{self.title}{flag_str}"

    @property
    def is_registration_open(self) -> bool:
        if self.status != HackathonStatus.LIVE:
            return False
        now = timezone.now()
        if self.registration_opens_at and now < self.registration_opens_at:
            return False
        if self.registration_closes_at and now >= self.registration_closes_at:
            return False
        return True


class ProblemStatement(TimeStampedModel):
    hackathon = models.ForeignKey(Hackathon, on_delete=models.CASCADE, related_name='problem_statements')
    # Generated by ProblemStatementService (PS-001, PS-002, ...) - never typed by admins.
    code = models.CharField(max_length=30, blank=True)
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    domain = models.CharField(max_length=100, blank=True)
    tags = models.JSONField(default=list, blank=True)
    max_teams = models.PositiveIntegerField(blank=True, null=True, help_text="Blank = unlimited.")
    is_active = models.BooleanField(default=True)
    order = models.IntegerField(default=0)

    class Meta:
        ordering = ['order', 'id']
        constraints = [
            models.UniqueConstraint(fields=['hackathon', 'code'], name='uniq_problem_statement_code_per_hackathon'),
        ]

    def __str__(self):
        return f"{self.code}: {self.title}"


class TeamStatus(models.TextChoices):
    FORMING = 'FORMING', 'Forming'
    REGISTERED = 'REGISTERED', 'Registered'
    DISQUALIFIED = 'DISQUALIFIED', 'Disqualified'
    WITHDRAWN = 'WITHDRAWN', 'Withdrawn'


class Team(TimeStampedModel):
    hackathon = models.ForeignKey(Hackathon, on_delete=models.CASCADE, related_name='teams')
    name = models.CharField(max_length=150)
    # SET_NULL, not CASCADE: deleting one user must not wipe the whole team
    # (other members + the team's Submission) along with them.
    leader = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name='led_teams')
    members = models.ManyToManyField(
        settings.AUTH_USER_MODEL, through='TeamMember', related_name='hackathon_teams', blank=True,
    )
    # SET_NULL, not PROTECT: PROTECT made deleting a whole hackathon fail (its
    # problem statements and teams cascade together). Deleting a statement
    # teams have picked is blocked explicitly in ProblemStatementDetailView.
    problem_statement = models.ForeignKey(
        ProblemStatement, on_delete=models.SET_NULL, null=True, blank=True, related_name='teams',
    )
    # Open innovation: instead of an admin-defined statement the team submits
    # its own problem. Mutually exclusive with `problem_statement`.
    is_open_innovation = models.BooleanField(default=False)
    custom_problem_title = models.CharField(max_length=255, blank=True)
    custom_problem_description = models.TextField(blank=True)
    custom_problem_domain = models.CharField(max_length=100, blank=True)
    status = models.CharField(max_length=20, choices=TeamStatus.choices, default=TeamStatus.FORMING)

    class Meta:
        constraints = [
            models.UniqueConstraint(Lower('name'), 'hackathon', name='uniq_team_name_per_hackathon_ci'),
        ]

    @property
    def open_innovation_code(self) -> str:
        return f"OI-{self.pk:03d}"

    def __str__(self):
        return f"Team '{self.name}' - {self.hackathon.title}"


class TeamRole(models.TextChoices):
    LEADER = 'LEADER', 'Leader'
    MEMBER = 'MEMBER', 'Member'


class TeamMember(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='memberships')
    # Denormalized from team.hackathon so the DB can enforce one team per
    # user per hackathon with a plain unique constraint.
    hackathon = models.ForeignKey(Hackathon, on_delete=models.CASCADE, related_name='memberships')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='hackathon_memberships')
    role = models.CharField(max_length=10, choices=TeamRole.choices, default=TeamRole.MEMBER)
    joined_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['joined_at', 'id']
        constraints = [
            models.UniqueConstraint(fields=['hackathon', 'user'], name='uniq_one_team_per_user_per_hackathon'),
        ]

    def save(self, *args, **kwargs):
        if not self.hackathon_id and self.team_id:
            self.hackathon_id = self.team.hackathon_id
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.user} in {self.team.name} ({self.role})"


class InviteStatus(models.TextChoices):
    PENDING = 'PENDING', 'Pending'
    ACCEPTED = 'ACCEPTED', 'Accepted'
    DECLINED = 'DECLINED', 'Declined'
    CANCELLED = 'CANCELLED', 'Cancelled'


class TeamInvite(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='invites')
    hackathon = models.ForeignKey(Hackathon, on_delete=models.CASCADE, related_name='team_invites')
    invited_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='hackathon_invites')
    invited_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name='+')
    status = models.CharField(max_length=10, choices=InviteStatus.choices, default=InviteStatus.PENDING)
    created_at = models.DateTimeField(auto_now_add=True)
    responded_at = models.DateTimeField(blank=True, null=True)

    class Meta:
        ordering = ['-created_at', '-id']
        constraints = [
            models.UniqueConstraint(
                fields=['team', 'invited_user'], condition=Q(status='PENDING'),
                name='uniq_pending_invite_per_team_user',
            ),
        ]

    def __str__(self):
        return f"Invite {self.invited_user} → {self.team.name} ({self.status})"


class RoundStatus(models.TextChoices):
    UPCOMING = 'UPCOMING', 'Upcoming'
    ACTIVE = 'ACTIVE', 'Active'
    COMPLETED = 'COMPLETED', 'Completed'


class Round(TimeStampedModel):
    hackathon = models.ForeignKey(Hackathon, on_delete=models.CASCADE, related_name='rounds')
    order = models.PositiveIntegerField()
    name = models.CharField(max_length=150)
    description = models.TextField(blank=True)
    starts_at = models.DateTimeField(blank=True, null=True)
    ends_at = models.DateTimeField(blank=True, null=True)
    status = models.CharField(max_length=10, choices=RoundStatus.choices, default=RoundStatus.UPCOMING)
    details_form = models.ForeignKey(
        Form, on_delete=models.SET_NULL, null=True, blank=True, related_name='hackathon_rounds',
        help_text="Form shortlisted teams' leaders fill in to (re-)submit details for this round.",
    )
    results_published = models.BooleanField(default=False)

    class Meta:
        ordering = ['order', 'id']
        constraints = [
            models.UniqueConstraint(fields=['hackathon', 'order'], name='uniq_round_order_per_hackathon'),
        ]

    def __str__(self):
        return f"{self.hackathon.title}, Round {self.order}: {self.name}"


class EntryStatus(models.TextChoices):
    PENDING = 'PENDING', 'Pending'
    SHORTLISTED = 'SHORTLISTED', 'Shortlisted'
    REJECTED = 'REJECTED', 'Not Shortlisted'


class RoundEntry(TimeStampedModel):
    round = models.ForeignKey(Round, on_delete=models.CASCADE, related_name='entries')
    team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='round_entries')
    status = models.CharField(max_length=12, choices=EntryStatus.choices, default=EntryStatus.PENDING)
    admin_notes = models.TextField(blank=True, help_text="Internal only, never shown to the team.")
    feedback = models.TextField(blank=True, help_text="Shown to the team once results are published.")
    decided_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name='+')
    decided_at = models.DateTimeField(blank=True, null=True)
    details_response = models.ForeignKey(
        FormResponse, on_delete=models.SET_NULL, null=True, blank=True, related_name='hackathon_round_entries',
    )

    class Meta:
        ordering = ['round__order', 'team__name']
        constraints = [
            models.UniqueConstraint(fields=['round', 'team'], name='uniq_round_entry_per_team'),
        ]

    def __str__(self):
        return f"{self.team.name} @ {self.round.name}: {self.status}"


class AnnouncementAudience(models.TextChoices):
    PUBLIC = 'PUBLIC', 'Everyone (public)'
    PARTICIPANTS = 'PARTICIPANTS', 'All registered participants'
    ROUND_ALL = 'ROUND_ALL', 'All teams in a round'
    ROUND_SHORTLISTED = 'ROUND_SHORTLISTED', 'Shortlisted teams in a round'
    TEAMS = 'TEAMS', 'Specific teams'


class HackathonAnnouncement(TimeStampedModel):
    hackathon = models.ForeignKey(Hackathon, on_delete=models.CASCADE, related_name='announcements')
    title = models.CharField(max_length=200)
    message = models.TextField()
    type = models.CharField(max_length=10, choices=AnnouncementType.choices, default=AnnouncementType.INFO)
    audience = models.CharField(max_length=20, choices=AnnouncementAudience.choices, default=AnnouncementAudience.PUBLIC)
    round = models.ForeignKey(Round, on_delete=models.CASCADE, null=True, blank=True, related_name='announcements')
    target_teams = models.ManyToManyField(Team, blank=True, related_name='targeted_announcements')
    is_active = models.BooleanField(default=True)
    publish_at = models.DateTimeField(default=timezone.now)
    expires_at = models.DateTimeField(blank=True, null=True)
    send_email = models.BooleanField(default=False)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name='+')

    class Meta:
        ordering = ['-publish_at', '-id']

    def __str__(self):
        return f"{self.title} ({self.audience})"


class Submission(TimeStampedModel):
    team = models.OneToOneField(Team, on_delete=models.CASCADE, related_name='submission')
    project_title = models.CharField(max_length=200)
    description = models.TextField()
    repo_url = models.URLField()
    demo_url = models.URLField(blank=True, null=True)
    video_url = models.URLField(blank=True, null=True)
    score = models.FloatField(default=0.0)

    def __str__(self):
        return f"Submission for {self.team.name}: {self.project_title}"
