# Generated by Django 5.2.17 on 2026-09-17 14:15

import apps.attendance.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms', '0017_form_attendance_days_form_attendance_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(db_index=True, default=apps.attendance.models.generate_badge_token, max_length=64, unique=True)),
                ('revoked', models.BooleanField(default=False, help_text='Revoked badges are rejected by the scan endpoint.')),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_badge', to='forms.response')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_index', models.PositiveIntegerField(help_text="0-based day offset from the form's attendance_start_date")),
                ('session_label', models.CharField(choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('EVENING', 'Evening')], max_length=20)),
                ('date', models.DateField()),
                ('opens_at', models.DateTimeField(blank=True, help_text='Scheduled start of this session', null=True)),
                ('closes_at', models.DateTimeField(blank=True, help_text='Scheduled end of this session', null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='forms.form')),
            ],
            options={
                'ordering': ['form', 'day_index', 'session_label'],
                'unique_together': {('form', 'day_index', 'session_label')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendancebadge')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_scans_performed', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendancesession')),
            ],
            options={
                'ordering': ['-scanned_at'],
                'unique_together': {('badge', 'session')},
            },
        ),
    ]
