# Generated by Django 5.2.17 on 2026-08-11 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('company_name', models.CharField(max_length=150)),
                ('job_type', models.CharField(choices=[('INTERNSHIP', 'Internship'), ('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time')], default='INTERNSHIP', max_length=20)),
                ('location', models.CharField(default='Remote / On-site', max_length=150)),
                ('salary_range', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('application_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms.form')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
