"""
Machine-readable error codes for the form validation engine.

Every FieldError carries one of these. They are stable identifiers the frontend
(and API consumers) can branch on without parsing human-readable messages.

Grouped by the validation layer that raises them:
  - STRUCTURAL  : the payload itself is malformed / references things it shouldn't
  - TYPE        : the value cannot be interpreted as the field's data type
  - REQUIRED    : a required (or conditionally-required) field is empty
  - RULE        : a configured ``validation_rules`` constraint failed
  - CHOICE      : a selection value is not one of the field's configured options
  - CROSS_FIELD : a rule comparing this field against another field failed
  - DEFINITION  : the form definition itself is invalid (publish-time only)
"""

# --- Structural / security ------------------------------------------------
UNKNOWN_FIELD = "UNKNOWN_FIELD"
FIELD_FROM_OTHER_FORM = "FIELD_FROM_OTHER_FORM"
DELETED_FIELD = "DELETED_FIELD"
DUPLICATE_ANSWER = "DUPLICATE_ANSWER"
SECTION_NOT_ANSWERABLE = "SECTION_NOT_ANSWERABLE"
MALFORMED_PAYLOAD = "MALFORMED_PAYLOAD"

# --- Type -----------------------------------------------------------------
INVALID_TYPE = "INVALID_TYPE"
INVALID_NUMBER = "INVALID_NUMBER"
INVALID_INTEGER = "INVALID_INTEGER"
INVALID_DATE = "INVALID_DATE"
INVALID_TIME = "INVALID_TIME"
INVALID_DATETIME = "INVALID_DATETIME"
INVALID_BOOLEAN = "INVALID_BOOLEAN"
EXPECTED_LIST = "EXPECTED_LIST"
EXPECTED_OBJECT = "EXPECTED_OBJECT"
EXPECTED_SCALAR = "EXPECTED_SCALAR"

# --- Required -----------------------------------------------------------------
REQUIRED = "REQUIRED"

# --- Format (short-answer / typed text) ----------------------------------
INVALID_EMAIL = "INVALID_EMAIL"
INVALID_URL = "INVALID_URL"
INVALID_PHONE = "INVALID_PHONE"
INVALID_FORMAT = "INVALID_FORMAT"
INVALID_USERNAME = "INVALID_USERNAME"
INVALID_SLUG = "INVALID_SLUG"
EMAIL_DOMAIN_NOT_ALLOWED = "EMAIL_DOMAIN_NOT_ALLOWED"
EMAIL_DOMAIN_BLOCKED = "EMAIL_DOMAIN_BLOCKED"

# --- Length / size constraints -----------------------------------------------
MIN_LENGTH = "MIN_LENGTH"
MAX_LENGTH = "MAX_LENGTH"
EXACT_LENGTH = "EXACT_LENGTH"
MIN_WORDS = "MIN_WORDS"
MAX_WORDS = "MAX_WORDS"
PATTERN_MISMATCH = "PATTERN_MISMATCH"
DISALLOWED_CHARACTER = "DISALLOWED_CHARACTER"
CHARACTER_NOT_ALLOWED = "CHARACTER_NOT_ALLOWED"
MUST_START_WITH = "MUST_START_WITH"
MUST_END_WITH = "MUST_END_WITH"
MUST_CONTAIN = "MUST_CONTAIN"
MUST_NOT_CONTAIN = "MUST_NOT_CONTAIN"

# --- Numeric constraints ----------------------------------------------------
MIN_VALUE = "MIN_VALUE"
MAX_VALUE = "MAX_VALUE"
EXACT_VALUE = "EXACT_VALUE"
NOT_GREATER_THAN = "NOT_GREATER_THAN"
NOT_GREATER_OR_EQUAL = "NOT_GREATER_OR_EQUAL"
NOT_LESS_THAN = "NOT_LESS_THAN"
NOT_LESS_OR_EQUAL = "NOT_LESS_OR_EQUAL"
MUST_BE_INTEGER = "MUST_BE_INTEGER"
MUST_BE_POSITIVE = "MUST_BE_POSITIVE"
NEGATIVE_NOT_ALLOWED = "NEGATIVE_NOT_ALLOWED"
NOT_MULTIPLE_OF = "NOT_MULTIPLE_OF"
OUT_OF_RANGE = "OUT_OF_RANGE"

# --- Date / time constraints -----------------------------------------------
DATE_TOO_EARLY = "DATE_TOO_EARLY"
DATE_TOO_LATE = "DATE_TOO_LATE"
TIME_TOO_EARLY = "TIME_TOO_EARLY"
TIME_TOO_LATE = "TIME_TOO_LATE"
DATE_MUST_BE_PAST = "DATE_MUST_BE_PAST"
DATE_MUST_BE_FUTURE = "DATE_MUST_BE_FUTURE"
DATE_TODAY_NOT_ALLOWED = "DATE_TODAY_NOT_ALLOWED"

# --- Choice / selection constraints ---------------------------------------
OPTION_NOT_ALLOWED = "OPTION_NOT_ALLOWED"
DUPLICATE_SELECTION = "DUPLICATE_SELECTION"
MIN_SELECTIONS = "MIN_SELECTIONS"
MAX_SELECTIONS = "MAX_SELECTIONS"
EXACT_SELECTIONS = "EXACT_SELECTIONS"

# --- Matrix / grid constraints ------------------------------------------------
UNKNOWN_MATRIX_ROW = "UNKNOWN_MATRIX_ROW"
UNKNOWN_MATRIX_COLUMN = "UNKNOWN_MATRIX_COLUMN"
MATRIX_ROW_REQUIRED = "MATRIX_ROW_REQUIRED"
MATRIX_MIN_PER_ROW = "MATRIX_MIN_PER_ROW"
MATRIX_MAX_PER_ROW = "MATRIX_MAX_PER_ROW"

# --- File constraints -------------------------------------------------------
FILE_TYPE_NOT_ALLOWED = "FILE_TYPE_NOT_ALLOWED"
FILE_TYPE_BLOCKED = "FILE_TYPE_BLOCKED"
FILE_TOO_LARGE = "FILE_TOO_LARGE"
FILE_TOO_SMALL = "FILE_TOO_SMALL"
TOO_MANY_FILES = "TOO_MANY_FILES"
TOO_FEW_FILES = "TOO_FEW_FILES"
INVALID_FILE_PAYLOAD = "INVALID_FILE_PAYLOAD"

# --- Cross-field ------------------------------------------------------------
CROSS_FIELD_MISMATCH = "CROSS_FIELD_MISMATCH"
CROSS_FIELD_REQUIRED = "CROSS_FIELD_REQUIRED"
CROSS_FIELD_ORDER = "CROSS_FIELD_ORDER"

# --- Form-definition (publish-time) ---------------------------------------
DEF_UNKNOWN_FIELD_TYPE = "DEF_UNKNOWN_FIELD_TYPE"
DEF_CHOICE_NEEDS_OPTIONS = "DEF_CHOICE_NEEDS_OPTIONS"
DEF_DUPLICATE_OPTION = "DEF_DUPLICATE_OPTION"
DEF_BLANK_OPTION = "DEF_BLANK_OPTION"
DEF_MATRIX_NEEDS_ROWS = "DEF_MATRIX_NEEDS_ROWS"
DEF_SCALE_RANGE_INVALID = "DEF_SCALE_RANGE_INVALID"
DEF_RULE_INCOMPATIBLE = "DEF_RULE_INCOMPATIBLE"
DEF_RULE_UNKNOWN_KEY = "DEF_RULE_UNKNOWN_KEY"
DEF_MIN_GREATER_THAN_MAX = "DEF_MIN_GREATER_THAN_MAX"
DEF_NEGATIVE_CONSTRAINT = "DEF_NEGATIVE_CONSTRAINT"
DEF_INVALID_REGEX = "DEF_INVALID_REGEX"
DEF_EMPTY_REGEX = "DEF_EMPTY_REGEX"
DEF_UNKNOWN_FORMAT = "DEF_UNKNOWN_FORMAT"
DEF_CONDITION_UNKNOWN_FIELD = "DEF_CONDITION_UNKNOWN_FIELD"
DEF_CONDITION_DELETED_FIELD = "DEF_CONDITION_DELETED_FIELD"
DEF_CONDITION_SELF_REFERENCE = "DEF_CONDITION_SELF_REFERENCE"
DEF_CONDITION_UNKNOWN_OPERATOR = "DEF_CONDITION_UNKNOWN_OPERATOR"
DEF_CONDITION_UNKNOWN_ACTION = "DEF_CONDITION_UNKNOWN_ACTION"
DEF_CONDITION_MALFORMED = "DEF_CONDITION_MALFORMED"
DEF_CROSS_FIELD_UNKNOWN_FIELD = "DEF_CROSS_FIELD_UNKNOWN_FIELD"
DEF_CROSS_FIELD_INCOMPATIBLE = "DEF_CROSS_FIELD_INCOMPATIBLE"

# --- Soft warnings (never block) -----------------------------------------
WARN_NO_REQUIRED_FIELDS = "WARN_NO_REQUIRED_FIELDS"
WARN_NO_FIELDS = "WARN_NO_FIELDS"
WARN_UNREACHABLE_CONDITION = "WARN_UNREACHABLE_CONDITION"
WARN_DUPLICATE_ORDER = "WARN_DUPLICATE_ORDER"
WARN_LEGACY_CONDITION_PLACEHOLDER = "WARN_LEGACY_CONDITION_PLACEHOLDER"
WARN_PARTIAL_MODE_REQUIRED = "WARN_PARTIAL_MODE_REQUIRED"


# Codes that a partial-mode (admin) import downgrades from error -> warning.
# Structural, type, choice-membership and form-definition problems always stay
# hard errors even in partial mode.
PARTIAL_MODE_DOWNGRADABLE = frozenset({
    REQUIRED,
    MIN_LENGTH, MAX_LENGTH, EXACT_LENGTH, MIN_WORDS, MAX_WORDS,
    PATTERN_MISMATCH, DISALLOWED_CHARACTER, CHARACTER_NOT_ALLOWED,
    MUST_START_WITH, MUST_END_WITH, MUST_CONTAIN, MUST_NOT_CONTAIN,
    MIN_VALUE, MAX_VALUE, EXACT_VALUE, NOT_GREATER_THAN, NOT_GREATER_OR_EQUAL,
    NOT_LESS_THAN, NOT_LESS_OR_EQUAL, MUST_BE_POSITIVE, NEGATIVE_NOT_ALLOWED,
    NOT_MULTIPLE_OF, OUT_OF_RANGE,
    DATE_TOO_EARLY, DATE_TOO_LATE, TIME_TOO_EARLY, TIME_TOO_LATE,
    DATE_MUST_BE_PAST, DATE_MUST_BE_FUTURE, DATE_TODAY_NOT_ALLOWED,
    MIN_SELECTIONS, MAX_SELECTIONS, EXACT_SELECTIONS,
    MATRIX_ROW_REQUIRED, MATRIX_MIN_PER_ROW, MATRIX_MAX_PER_ROW,
    FILE_TOO_LARGE, FILE_TOO_SMALL, TOO_MANY_FILES, TOO_FEW_FILES,
    EMAIL_DOMAIN_NOT_ALLOWED, EMAIL_DOMAIN_BLOCKED,
    CROSS_FIELD_MISMATCH, CROSS_FIELD_REQUIRED, CROSS_FIELD_ORDER,
})
