# Generated by Django 5.2.17 on 2026-10-08 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0022_form_confirmation_notification_enabled_and_more'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='response',
            field=models.ForeignKey(blank=True, help_text='Optional link to a forms.Response when generated by form automation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='forms.response'),
        ),
    ]
